--
-- CONDS  (Table) 
--
--  Dependencies: 
--   CONDS (Table)
--
--   Row Count: 16715
CREATE TABLE OPAL_FRA.CONDS
(
  OP_SIGN    VARCHAR2(30 CHAR),
  PARENT_ID  INTEGER,
  IS_LEAF    INTEGER,
  GH         CHAR(1 BYTE)                       DEFAULT 'G',
  ORDNO      INTEGER,
  DESCR      VARCHAR2(30 CHAR),
  ID         INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 356399 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE OPAL_FRA.CONDS IS 'Description of condition trees in queries';

COMMENT ON COLUMN OPAL_FRA.CONDS.OP_SIGN IS 'Logical operation (AND/OR/CASE), empty for leaf nodes';

COMMENT ON COLUMN OPAL_FRA.CONDS.PARENT_ID IS 'Parent node of the tree';

COMMENT ON COLUMN OPAL_FRA.CONDS.IS_LEAF IS '1 - leaf node';

COMMENT ON COLUMN OPAL_FRA.CONDS.GH IS 'G-used in GROUP BY, H - used in HAVING, C - for conditional groups';

COMMENT ON COLUMN OPAL_FRA.CONDS.ORDNO IS 'Order number for the parent node';

COMMENT ON COLUMN OPAL_FRA.CONDS.DESCR IS 'Only for work with a bad front end';