--
-- EXPRS  (Table) 
--
--   Row Count: 43
CREATE TABLE OPAL_FRA.EXPRS
(
  OP_SIGN    VARCHAR2(30 CHAR),
  PARENT_ID  INTEGER,
  IS_LEAF    INTEGER,
  ORDNO      INTEGER,
  DESCR      VARCHAR2(30 CHAR)                  NOT NULL,
  ID         INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 103 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  RS_EXPR    VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE OPAL_FRA.EXPRS IS 'Expression trees of the system';

COMMENT ON COLUMN OPAL_FRA.EXPRS.OP_SIGN IS 'Sign of operation, not needed for tree leafs';

COMMENT ON COLUMN OPAL_FRA.EXPRS.PARENT_ID IS 'Parent node in the expression tree';

COMMENT ON COLUMN OPAL_FRA.EXPRS.IS_LEAF IS '1 - leaf';

COMMENT ON COLUMN OPAL_FRA.EXPRS.ORDNO IS 'Order number for the walk by the descendants of the same node';

COMMENT ON COLUMN OPAL_FRA.EXPRS.DESCR IS 'Description, only for work in a bad front end';