-- 
-- AREAS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    AREAS (Table)
ALTER TABLE OPAL_FRA.AREAS ADD (
  CONSTRAINT R_AREAS_P 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES OPAL_FRA.AREAS (ID)
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE);