-- 
-- ATTRS2CUBES  (Table Foreign Keys)
-- 
-- Dependencies: 
--    ATTRS (Table)
--    CUBES (Table)
--    ELEM_RECS (Table)
ALTER TABLE OPAL_FRA.ATTRS2CUBES ADD (
  CONSTRAINT R_ATTRS2CUBES_A 
  FOREIGN KEY (ATTR_ID) 
  REFERENCES OPAL_FRA.ATTRS (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.ATTRS2CUBES ADD (
  CONSTRAINT R_ATTRS2CUBES_C 
  FOREIGN KEY (CUBE_ID) 
  REFERENCES OPAL_FRA.CUBES (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.ATTRS2CUBES ADD (
  CONSTRAINT R_ATTRS2CUBES_E 
  FOREIGN KEY (ELEM_REC_ID) 
  REFERENCES OPAL_FRA.ELEM_RECS (ID)
  ENABLE VALIDATE);