-- 
-- ATTRS2RECS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    ATTRS (Table)
--    ELEM_RECS (Table)
ALTER TABLE OPAL_FRA.ATTRS2RECS ADD (
  CONSTRAINT R_ATTRS2RECS_A 
  FOREIGN KEY (ATTR_ID) 
  REFERENCES OPAL_FRA.ATTRS (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.ATTRS2RECS ADD (
  CONSTRAINT R_ATTRS2RECS_R 
  FOREIGN KEY (ELEM_REC_ID) 
  REFERENCES OPAL_FRA.ELEM_RECS (ID)
  ENABLE VALIDATE);