ALTER TABLE OPAL_FRA.ATTR_TYPES ADD (
  CONSTRAINT C_ATTR_TYPES_CD
  CHECK (rtrim(nvl(cd, '@'), 'CD') is null)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.ATTR_TYPES ADD (
  CONSTRAINT C_ATTR_TYPES_K
  CHECK (nvl(type_kind, '@') in ('B', 'D', 'N'))
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.ATTR_TYPES ADD (
  CONSTRAINT P_ATTR_TYPES
  PRIMARY KEY
  (ID)
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.ATTR_TYPES ADD (
  CONSTRAINT U_ATTR_TYPES_IT
  UNIQUE (ID, TYPE_KIND)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.ATTR_TYPES ADD (
  CONSTRAINT U_ATTR_TYPES_S
  UNIQUE (SCODE)
  ENABLE VALIDATE);