-- 
-- ATTR_TYPES  (Table Foreign Keys)
-- 
-- Dependencies: 
--    DOMAINS (Table)
--    ATTR_TYPES (Table)
ALTER TABLE OPAL_FRA.ATTR_TYPES ADD (
  CONSTRAINT R_ATTR_TYPES_DO 
  FOREIGN KEY (DOM_ID) 
  REFERENCES OPAL_FRA.DOMAINS (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.ATTR_TYPES ADD (
  CONSTRAINT R_ATTR_TYPES_P 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES OPAL_FRA.ATTR_TYPES (ID)
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE);