ALTER TABLE OPAL_FRA.CATEGORIES ADD (
  CONSTRAINT P_CATEGORIES
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.CATEGORIES ADD (
  CONSTRAINT U_CATEGORIES#A
  UNIQUE (AREA_ID, ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.CATEGORIES ADD (
  CONSTRAINT U_CATEGORIES#N
  UNIQUE (NAME, AREA_ID)
  ENABLE VALIDATE);