-- 
-- CONDS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    CONDS (Table)
ALTER TABLE OPAL_FRA.CONDS ADD (
  CONSTRAINT R_CONDS_P 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES OPAL_FRA.CONDS (ID)
  ON DELETE CASCADE
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE);