ALTER TABLE OPAL_FRA.DIM_LEVELS ADD (
  CONSTRAINT C_DIM_LEVELS#STORAGE
  CHECK (storage_type<0)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.DIM_LEVELS ADD (
  CONSTRAINT P_DIM_LEVELS
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.DIM_LEVELS ADD (
  CONSTRAINT U_DIM_LEVELS_DO
  UNIQUE (DIM_ID, ORDNO)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.DIM_LEVELS ADD (
  CONSTRAINT U_DIM_LEVELS_IS
  UNIQUE (ID, STORAGE_TYPE)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.DIM_LEVELS ADD (
  CONSTRAINT U_DIM_LEVELS_S
  UNIQUE (SCODE)
  ENABLE VALIDATE);