-- 
-- DIM_LEVELS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    DIMS (Table)
--    ATTR_TYPES (Table)
ALTER TABLE OPAL_FRA.DIM_LEVELS ADD (
  CONSTRAINT R_DIM_LEVELS_D 
  FOREIGN KEY (DIM_ID, DOM_ID) 
  REFERENCES OPAL_FRA.DIMS (ID, DOM_ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.DIM_LEVELS ADD (
  CONSTRAINT R_DIM_LEVELS_S 
  FOREIGN KEY (STORAGE_TYPE) 
  REFERENCES OPAL_FRA.ATTR_TYPES (ID)
  ENABLE VALIDATE);