-- 
-- DIMS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    DOMAINS (Table)
--    DIMS (Table)
ALTER TABLE OPAL_FRA.DIMS ADD (
  CONSTRAINT R_DIMS_DOMS 
  FOREIGN KEY (DOM_ID) 
  REFERENCES OPAL_FRA.DOMAINS (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.DIMS ADD (
  CONSTRAINT R_DIMS_P 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES OPAL_FRA.DIMS (ID)
  ENABLE VALIDATE);