-- 
-- EXPRS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    EXPRS (Table)
ALTER TABLE OPAL_FRA.EXPRS ADD (
  CONSTRAINT R_EXPRS_P 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES OPAL_FRA.EXPRS (ID)
  ON DELETE CASCADE
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE);