-- 
-- FOLDERS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    FOLDERS (Table)
ALTER TABLE OPAL_FRA.FOLDERS ADD (
  CONSTRAINT R_FOLDERS_P 
  FOREIGN KEY (PID) 
  REFERENCES OPAL_FRA.FOLDERS (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);