ALTER TABLE OPAL_FRA.FUNC_GRP ADD (
  CONSTRAINT C_FUNC_GRP_TYPE
  CHECK (nvl(grp_type, 0) in (1,2))
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.FUNC_GRP ADD (
  CONSTRAINT P_FUNC_GRP
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);