ALTER TABLE OPAL_FRA.FUNC_ROW_ ADD (
  CONSTRAINT C_FUNC_ROW_PT
  CHECK (par_type<>0)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.FUNC_ROW_ ADD (
  CONSTRAINT C_FUNC_ROW_T
  CHECK (func_type in ('O','U','S'))
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.FUNC_ROW_ ADD (
  CONSTRAINT P_FUNC_ROW
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.FUNC_ROW_ ADD (
  CONSTRAINT U_FUNC_ROW_IP
  UNIQUE (ID, PAR_TYPE)
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE);