-- 
-- GROUPS_GL  (Table Foreign Keys)
-- 
-- Dependencies: 
--    GROUPS_GL (Table)
--    GRP_TREE (Table)
ALTER TABLE OPAL_FRA.GROUPS_GL ADD (
  CONSTRAINT R_GROUPS_GL_P 
  FOREIGN KEY (GL_PID) 
  REFERENCES OPAL_FRA.GROUPS_GL (GL_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.GROUPS_GL ADD (
  CONSTRAINT R_GROUPS_GL_TREE 
  FOREIGN KEY (ID, PID, DATE_FROM) 
  REFERENCES OPAL_FRA.GRP_TREE (ID, PARENT_ID, DATE_FROM)
  ON DELETE CASCADE
  ENABLE VALIDATE);