-- 
-- GRP_C  (Table Foreign Keys)
-- 
-- Dependencies: 
--    CONDS (Table)
--    GROUPS (Table)
ALTER TABLE OPAL_FRA.GRP_C ADD (
  CONSTRAINT R_GRP_C_C 
  FOREIGN KEY (COND_ID) 
  REFERENCES OPAL_FRA.CONDS (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.GRP_C ADD (
  CONSTRAINT R_GRP_C_G 
  FOREIGN KEY (GRP_ID, GRP_TYPE) 
  REFERENCES OPAL_FRA.GROUPS (ID, GRP_TYPE)
  ON DELETE CASCADE
  ENABLE VALIDATE);