ALTER TABLE OPAL_FRA.GRP_C ADD (
  CONSTRAINT C_GRP_C_L
  CHECK (nvl(is_leaf, 1)=1)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.GRP_C ADD (
  CONSTRAINT C_GRP_C_T
  CHECK (nvl(grp_type, '@')='C')
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.GRP_C ADD (
  CONSTRAINT P_GRP_TYPE_G
  PRIMARY KEY
  (GRP_ID)
  ENABLE VALIDATE);