ALTER TABLE OPAL_FRA.LEAFS4EXPRS ADD (
  CONSTRAINT C_LEAFS4EXPRS_CA
  CHECK (attr_id is null and const is not null or  attr_id is not null and const is null)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.LEAFS4EXPRS ADD (
  CONSTRAINT C_LEAFS4EXPRS_I
  CHECK (nvl(is_leaf, 0)=1)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.LEAFS4EXPRS ADD (
  CONSTRAINT C_LEAFS4EXPRS_U
  CHECK (un_sign is null or un_sign='-')
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.LEAFS4EXPRS ADD (
  CONSTRAINT U_LEAFS4EXPRS_L
  UNIQUE (LEAF_ID)
  ENABLE VALIDATE);