-- 
-- LEAFS4EXPRS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    ATTRS (Table)
--    FUNC_ROW_ (Table)
--    EXPRS (Table)
ALTER TABLE OPAL_FRA.LEAFS4EXPRS ADD (
  CONSTRAINT R_LEAFS4EXPRS_A 
  FOREIGN KEY (ATTR_ID) 
  REFERENCES OPAL_FRA.ATTRS (ID)
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.LEAFS4EXPRS ADD (
  CONSTRAINT R_LEAFS4EXPRS_F 
  FOREIGN KEY (FUNC_ROW_ID) 
  REFERENCES OPAL_FRA.FUNC_ROW_ (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.LEAFS4EXPRS ADD (
  CONSTRAINT R_LEAFS4EXPRS_LI 
  FOREIGN KEY (LEAF_ID, IS_LEAF) 
  REFERENCES OPAL_FRA.EXPRS (ID, IS_LEAF)
  ON DELETE CASCADE
  ENABLE VALIDATE);