ALTER TABLE OPAL_FRA.OBJ_COL_IDS ADD (
  CONSTRAINT P_OBJ_COL_IDS
  PRIMARY KEY
  (COL_ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.OBJ_COL_IDS ADD (
  CONSTRAINT U_OBJ_COL_IDS_INO
  UNIQUE (OBJ_ID, COL_ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.OBJ_COL_IDS ADD (
  CONSTRAINT U_OBJ_COL_IDS_ONM
  UNIQUE (OBJ_ID, COL_NAME)
  ENABLE VALIDATE);