ALTER TABLE OPAL_FRA.OPS4TYPES ADD (
  CONSTRAINT C_OPS4TYPES_OP_KIND
  CHECK (nvl(op_kind, '.')='L')
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.OPS4TYPES ADD (
  CONSTRAINT C_OPS4TYPES_TYPE_KIND
  CHECK (nvl(type_kind, '.')='B')
  ENABLE VALIDATE);