-- 
-- OPS4TYPES  (Table Foreign Keys)
-- 
-- Dependencies: 
--    OPS (Table)
--    ATTR_TYPES (Table)
ALTER TABLE OPAL_FRA.OPS4TYPES ADD (
  CONSTRAINT R_OPS4TYPES_O 
  FOREIGN KEY (OP_SIGN, OP_KIND) 
  REFERENCES OPAL_FRA.OPS (OP_SIGN, OP_KIND)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.OPS4TYPES ADD (
  CONSTRAINT R_OPS4TYPES_T 
  FOREIGN KEY (TYPE_ID, TYPE_KIND) 
  REFERENCES OPAL_FRA.ATTR_TYPES (ID, TYPE_KIND)
  ENABLE VALIDATE);