-- 
-- PARAMS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    OPAL_DATA_FRA.TASKS (Table)
ALTER TABLE OPAL_FRA.PARAMS ADD (
  CONSTRAINT R_PARAMS_T 
  FOREIGN KEY (TASKID) 
  REFERENCES OPAL_DATA_FRA.TASKS (TASKID)
  ENABLE VALIDATE);