-- 
-- QRYS2FOLDERS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    FOLDERS (Table)
--    QRYS (Table)
ALTER TABLE OPAL_FRA.QRYS2FOLDERS ADD (
  CONSTRAINT R_QRYS2FOLDERS_F 
  FOREIGN KEY (FOLDER_ID) 
  REFERENCES OPAL_FRA.FOLDERS (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.QRYS2FOLDERS ADD (
  CONSTRAINT R_QRYS2FOLDERS_Q 
  FOREIGN KEY (QRY_ID) 
  REFERENCES OPAL_FRA.QRYS (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);