-- 
-- QRYS_SEL  (Table Foreign Keys)
-- 
-- Dependencies: 
--    ATTRS2CUBES (Table)
--    DIM_LEVELS (Table)
--    FUNC_GRP (Table)
--    GROUPS (Table)
--    QRYS (Table)
ALTER TABLE OPAL_FRA.QRYS_SEL ADD (
  CONSTRAINT R_QRYS_SEL_AC 
  FOREIGN KEY (ATTR_ID, CUBE_ID) 
  REFERENCES OPAL_FRA.ATTRS2CUBES (ATTR_ID, CUBE_ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.QRYS_SEL ADD (
  CONSTRAINT R_QRYS_SEL_D 
  FOREIGN KEY (DIM_LEV_ID) 
  REFERENCES OPAL_FRA.DIM_LEVELS (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.QRYS_SEL ADD (
  CONSTRAINT R_QRYS_SEL_F 
  FOREIGN KEY (FUNC_GRP_ID) 
  REFERENCES OPAL_FRA.FUNC_GRP (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.QRYS_SEL ADD (
  CONSTRAINT R_QRYS_SEL_GRP 
  FOREIGN KEY (GRP_ID) 
  REFERENCES OPAL_FRA.GROUPS (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.QRYS_SEL ADD (
  CONSTRAINT R_QRYS_SEL_QC 
  FOREIGN KEY (QRY_ID, CUBE_ID) 
  REFERENCES OPAL_FRA.QRYS (ID, CUBE_ID)
  ENABLE VALIDATE);