-- 
-- QRYS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    QRYS (Table)
--    CUBES (Table)
--    QUERY_TYPES (Table)
--    CONDS (Table)
--    CONDS (Table)
ALTER TABLE OPAL_FRA.QRYS ADD (
  CONSTRAINT R_QRYS#TMP 
  FOREIGN KEY (TMP_QRY_ID) 
  REFERENCES OPAL_FRA.QRYS (ID)
  ON DELETE CASCADE
  DISABLE NOVALIDATE);

ALTER TABLE OPAL_FRA.QRYS ADD (
  CONSTRAINT R_QRYS_C 
  FOREIGN KEY (CUBE_ID) 
  REFERENCES OPAL_FRA.CUBES (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.QRYS ADD (
  CONSTRAINT R_QRYS_T 
  FOREIGN KEY (QRY_TYPE) 
  REFERENCES OPAL_FRA.QUERY_TYPES (ID)
  DISABLE NOVALIDATE);

ALTER TABLE OPAL_FRA.QRYS ADD (
  CONSTRAINT R_QRYS_W 
  FOREIGN KEY (WHERE_ID) 
  REFERENCES OPAL_FRA.CONDS (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.QRYS ADD (
  CONSTRAINT R_QRY_H 
  FOREIGN KEY (HAVING_ID) 
  REFERENCES OPAL_FRA.CONDS (ID)
  ENABLE VALIDATE);