ALTER TABLE OPAL_FRA.QRYS ADD (
  CONSTRAINT C_QRYS#PRIVATE
  CHECK (is_private in ('R', 'N', 'P'))
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.QRYS ADD (
  CONSTRAINT C_QRYS_P
  CHECK (nvl(predefined, '@') in ('Y','N'))
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.QRYS ADD (
  CONSTRAINT P_QRYS
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.QRYS ADD (
  CONSTRAINT U_QRYS_ABBR
  UNIQUE (ABBR, VERSION_NO)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.QRYS ADD (
  CONSTRAINT U_QRYS_QC
  UNIQUE (ID, CUBE_ID)
  ENABLE VALIDATE);