-- 
-- RECS2CUBES  (Table Foreign Keys)
-- 
-- Dependencies: 
--    ELEM_RECS (Table)
--    CUBES (Table)
--    ELEM_RECS (Table)
ALTER TABLE OPAL_FRA.RECS2CUBES ADD (
  CONSTRAINT R_REC2CUBES_R 
  FOREIGN KEY (ELEM_REC_ID) 
  REFERENCES OPAL_FRA.ELEM_RECS (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.RECS2CUBES ADD (
  CONSTRAINT R_RECS2CUBES_C 
  FOREIGN KEY (CUBE_ID) 
  REFERENCES OPAL_FRA.CUBES (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.RECS2CUBES ADD (
  CONSTRAINT R_RECS2CUBES_P 
  FOREIGN KEY (PARENT_ID) 
  REFERENCES OPAL_FRA.ELEM_RECS (ID)
  ENABLE VALIDATE);