ALTER TABLE OPAL_FRA.RECS2CUBES ADD (
  CONSTRAINT C_RECS2CUBES_H
  CHECK (how_much in ('1','C', 'N'))
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.RECS2CUBES ADD (
  CONSTRAINT C_RECS2CUBES_PH
  CHECK (parent_id is null and how_much is null or
  parent_id is not null and how_much is not null)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.RECS2CUBES ADD (
  CONSTRAINT U_REC2CUBES_IE
  UNIQUE (CUBE_ID, ELEM_REC_ID)
  ENABLE VALIDATE);