-- 
-- RS_CODES4DIMS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    DIM_LEVELS (Table)
ALTER TABLE OPAL_FRA.RS_CODES4DIMS ADD (
  CONSTRAINT R_RS_CODES4DIMS_D 
  FOREIGN KEY (DIM_LEV_ID) 
  REFERENCES OPAL_FRA.DIM_LEVELS (ID)
  ENABLE VALIDATE);