ALTER TABLE OPAL_FRA.RS_CODES4DIMS ADD (
  CONSTRAINT P_RS_CODES4DIMS_DC
  PRIMARY KEY
  (DIM_LEV_ID, ATTR_TYPE_CODE)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.RS_CODES4DIMS ADD (
  CONSTRAINT U_RS_CODES4DIMS_SCODE
  UNIQUE (SCODE)
  ENABLE VALIDATE);