-- 
-- TMP_GROUPS  (Table Foreign Keys)
-- 
-- Dependencies: 
--    QRYS (Table)
ALTER TABLE OPAL_FRA.TMP_GROUPS ADD (
  CONSTRAINT R_TMP_GROUPS#Q 
  FOREIGN KEY (QRY_ID) 
  REFERENCES OPAL_FRA.QRYS (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);