-- 
-- TYPES_COMP  (Table Foreign Keys)
-- 
-- Dependencies: 
--    ATTR_TYPES (Table)
--    DIM_LEVELS (Table)
--    FUNC_ROW_ (Table)
--    ATTR_TYPES (Table)
--    FUNC_ROW_ (Table)
--    FUNC_ROW_ (Table)
ALTER TABLE OPAL_FRA.TYPES_COMP ADD (
  CONSTRAINT R_TYPES_COMP_C 
  FOREIGN KEY (COMP_TYPE_ID) 
  REFERENCES OPAL_FRA.ATTR_TYPES (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.TYPES_COMP ADD (
  CONSTRAINT R_TYPES_COMP_CS 
  FOREIGN KEY (COMP_TYPE_ID, STORAGE_TYPE) 
  REFERENCES OPAL_FRA.DIM_LEVELS (ID, STORAGE_TYPE)
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.TYPES_COMP ADD (
  CONSTRAINT R_TYPES_COMP_FB 
  FOREIGN KEY (FUN_ROW_BACK) 
  REFERENCES OPAL_FRA.FUNC_ROW_ (ID)
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.TYPES_COMP ADD (
  CONSTRAINT R_TYPES_COMP_T 
  FOREIGN KEY (TYPE_ID) 
  REFERENCES OPAL_FRA.ATTR_TYPES (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.TYPES_COMP ADD (
  CONSTRAINT R_TYPES_COMP_TF 
  FOREIGN KEY (FUN_ROW_CONV, TYPE_ID) 
  REFERENCES OPAL_FRA.FUNC_ROW_ (ID, PAR_TYPE)
  DEFERRABLE INITIALLY DEFERRED
  ENABLE VALIDATE);

ALTER TABLE OPAL_FRA.TYPES_COMP ADD (
  CONSTRAINT R_TYPES_CONV_F 
  FOREIGN KEY (FUN_ROW_CONV) 
  REFERENCES OPAL_FRA.FUNC_ROW_ (ID)
  ENABLE VALIDATE);